import type { Metadata } from "next";
import Script from "next/script";
import Navbar from "../components/layouts/Navbar";
import Footer from "../components/layouts/Footer";
import styles from "./page.module.css";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
      </head>
      <body>
        <Script
          src="https://cdn.tailwindcss.com"
          strategy="beforeInteractive"
        />
        <Navbar />
        <div className={styles.page}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
